### ISSUE TITLE
Supporting attributes without values

### ISSUE THREAD

**Issue by atomrc** [jvanbruegge/tree-selector#2]
Hi,

The `README` mentions that only attribute with non false-y value will be matched when using the `[attr]` pattern. 
Is there a reason for that? 

On the browser `document.querySelectorAll('[attr]')` will also match elements that have `attr` with a falsy value. Could be a good idea to align those behaviors, what do you think?

Also, regarding the `[attr]` selector, we seem to have trouble using it on `snabbdom-selector` (see this issue https://github.com/TylorS/snabbdom-selector/issues/30)

Any idea what could happen here?

Thanks

**Comment by jvanbruegge** [comment]
Ok, yeah, probably me misunderstanding the behavior of `document.querySelector`
Will try to fix that tomorrow
